(() => {
  "use strict";
  const { $, $$, el, svgEl, clear, setText, fileURL, tileURL, pad2, loadManifest, revealPage } = window.WJY;

  if (window.gsap && window.ScrollTrigger) gsap.registerPlugin(ScrollTrigger);

  // Per-entry poster image generated by ffmpeg (see thumbnails/ directory).
  const posterURL = (id) => "thumbnails/" + encodeURIComponent(id) + ".jpg";

  // ---------- State ----------
  const FILTER_DEFS = [
    { id: "ALL",     label: "All",     test: () => true },
    { id: "WEB",     label: "Web",     test: (e) => e.kind === "Web" },
    { id: "PRODUCT", label: "Product", test: (e) => e.kind === "Product" },
    { id: "CONCEPT", label: "Concept", test: (e) => e.kind === "Concept" },
    { id: "MOTION",  label: "Motion",  test: (e) => e.kind === "Motion" }
  ];

  const state = {
    entries: [],                  // all 42
    filter: "ALL",                // current filter id
    filtered: [],                 // entries.filter(byCurrentFilter)
    idx: 0,                       // index within filtered
    view: "slider",               // 'slider' | 'list'
    modalOpen: false,
    modalIdx: 0                   // index within filtered when modal opens
  };

  // ---------- Helpers ----------

  function applyFilter(id) {
    const def = FILTER_DEFS.find((f) => f.id === id) || FILTER_DEFS[0];
    state.filter = def.id;
    state.filtered = state.entries.filter(def.test);
    state.idx = 0;
  }

  function currentEntry() { return state.filtered[state.idx] || null; }
  function prevIdx() { const n = state.filtered.length; return (state.idx - 1 + n) % n; }
  function nextIdx() { const n = state.filtered.length; return (state.idx + 1) % n; }
  function entryAt(i) { return state.filtered[((i % state.filtered.length) + state.filtered.length) % state.filtered.length]; }

  // ---------- Render: scale markers ----------

  function renderScaleMarkers() {
    const fragments = [];
    for (let n = 0; n <= 77; n += 1) fragments.push(String(n).padStart(3, "0"));
    [$("[data-scale-left]"), $("[data-scale-right]")].forEach((host) => {
      if (!host) return;
      clear(host);
      fragments.forEach((f) => host.appendChild(el("span", { class: "scale__num", text: f })));
    });
  }

  // ---------- Render: filter chips ----------

  function renderFilters() {
    const host = $("[data-filters]");
    if (!host) return;
    clear(host);
    FILTER_DEFS.forEach((f) => {
      const count = state.entries.filter(f.test).length;
      const isActive = f.id === state.filter;
      const btn = el("button", {
        class: "filter" + (isActive ? " filter--active" : ""),
        type: "button",
        "data-filter-id": f.id,
        role: "tab",
        "aria-selected": String(isActive)
      },
        el("span", { class: "filter__dot" }),
        el("span", { class: "filter__label", text: f.label })
      );
      host.appendChild(btn);
    });
  }

  // ---------- Render: slider (current entry into center frame + meta + floaters) ----------

  function renderSlider() {
    const cur = currentEntry();
    if (!cur) return;
    const total = state.filtered.length;

    // Above frame: kind
    setText($("[data-frame-kind]"), (cur.kind || "").toUpperCase());

    // Below frame: pagination — index + title only (no trailing category/total)
    setText($("[data-frame-num]"),   pad2(state.idx + 1) + ".");
    setText($("[data-frame-title]"), (cur.title || "").toUpperCase());
    setText($("[data-frame-total]"), "");

    // Center video AND bg video — same source, played in two places.
    // Set poster first so an image is visible immediately while the video loads.
    // The center frame loads eagerly; the bg-video is deferred until the center frame
    // can play, so initial page load fetches one video instead of two in parallel.
    const part = cur.parts && cur.parts[0];
    const frameVideo = $("[data-frame-video]");
    const bgVideo    = $("[data-bg-video]");
    if (part) {
      const newSrc = tileURL(part.file);
      const newPoster = posterURL(cur.id);
      const swap = (v) => {
        if (!v) return;
        v.poster = newPoster;
        if (v.getAttribute("src") === newSrc) { v.play().catch(() => {}); return; }
        v.src = newSrc;
        v.load();
        v.play().catch(() => {});
      };
      swap(frameVideo);
      // Defer the bg-video until the center frame is ready so we don't fetch two
      // copies of the same source in parallel on first paint.
      const startBg = () => swap(bgVideo);
      if (frameVideo && frameVideo.readyState < 3) {
        frameVideo.addEventListener("canplay", startBg, { once: true });
      } else {
        startBg();
      }
    }

    // Floaters: prev + next thumbs.
    // Default state: poster image only at reduced opacity (CSS), so they don't compete
    // with the center video. On hover (CSS opacity → 1, JS .play()) the muted clip plays.
    // We prefetch them after the center frame is ready so the next/prev clips are warm
    // by the time the user scrolls or hovers, without competing for bandwidth on first paint.
    const prev = entryAt(state.idx - 1);
    const next = entryAt(state.idx + 1);
    const prevVid = $("[data-floater-prev-video]");
    const nextVid = $("[data-floater-next-video]");
    const wireFloaterVideo = (v, entry) => {
      if (!v || !entry || !entry.parts || !entry.parts[0]) return;
      v.poster = posterURL(entry.id);
      const src = tileURL(entry.parts[0].file);
      if (v.getAttribute("src") !== src) {
        v.pause();
        v.src = src;
      }
    };
    wireFloaterVideo(prevVid, prev);
    wireFloaterVideo(nextVid, next);

    const prefetchFloater = (v) => {
      if (!v || !v.getAttribute("src")) return;
      // Bump preload so the browser starts fetching. Hover-play still works as before.
      v.preload = "auto";
      v.load();
    };
    const prefetchFloaters = () => { prefetchFloater(prevVid); prefetchFloater(nextVid); };
    if (frameVideo && frameVideo.readyState < 3) {
      frameVideo.addEventListener("canplay", prefetchFloaters, { once: true });
    } else {
      prefetchFloaters();
    }
  }

  // ---------- Render: list ----------

  function buildListRow(entry, i) {
    const part = entry.parts && entry.parts[0];
    const video = part
      ? el("video", {
          class: "list__video",
          src: tileURL(part.file),
          poster: posterURL(entry.id),
          muted: true, playsinline: true, preload: "none", loop: true,
          disablepictureinpicture: true
        })
      : null;
    // Dynamically-created <video> elements need the IDL property set explicitly —
    // setAttribute("muted") alone is not always honored at playback time.
    if (video) video.muted = true;
    const media = el("div", { class: "list__media" }, video);
    return el("li", { class: "list__row", "data-list-row": true, "data-idx": String(i) },
      el("button", { class: "list__btn", type: "button" },
        el("span", { class: "list__num",   text: pad2(i + 1) + "." }),
        el("h3",   { class: "list__title", text: (entry.title || "").toUpperCase() }),
        el("span", { class: "list__kind",  text: (entry.kind || "").toUpperCase() }),
        media
      )
    );
  }

  function renderList() {
    const host = $("[data-list-rows]");
    if (!host) return;
    clear(host);
    state.filtered.forEach((entry, i) => host.appendChild(buildListRow(entry, i)));
  }

  function setView(name) {
    state.view = name;
    const slider = $("[data-slider]");
    const list   = $("[data-list]");
    if (slider) slider.hidden = (name !== "slider");
    if (list)   list.hidden   = (name !== "list");
    $$("[data-view-set]").forEach((b) => {
      const isActive = b.getAttribute("data-view-set") === name;
      b.classList.toggle("viewtoggle__btn--active", isActive);
      b.setAttribute("aria-selected", String(isActive));
    });
    document.body.classList.toggle("is-list", name === "list");
  }

  function bindListHover() {
    const host = $("[data-list-rows]");
    if (!host) return;
    host.addEventListener("pointerenter", (ev) => {
      const row = ev.target.closest("[data-list-row]");
      if (!row) return;
      const v = row.querySelector("video");
      if (v) v.play().catch(() => {});
    }, true);
    host.addEventListener("pointerleave", (ev) => {
      const row = ev.target.closest("[data-list-row]");
      if (!row) return;
      const v = row.querySelector("video");
      if (v) v.pause();
    }, true);
  }

  function wireViewToggle() {
    const toggle = $("[data-view-toggle]");
    if (!toggle) return;
    toggle.addEventListener("click", (ev) => {
      const btn = ev.target.closest("[data-view-set]");
      if (!btn) return;
      const target = btn.getAttribute("data-view-set");
      if (target && target !== state.view) setView(target);
    });
  }

  // ---------- Render error ----------

  function renderError(message) {
    const main = $("[data-stage]");
    if (!main) return;
    clear(main);
    main.appendChild(el("div", { class: "error" },
      el("h2", { text: "Couldn't load the archive" }),
      el("p", { text: message })
    ));
  }

  // ---------- Modal player ----------

  function renderModalParts(entry) {
    const host = $("[data-modal-parts]");
    if (!host) return;
    clear(host);
    const parts = entry.parts || [];
    if (parts.length <= 1) return;
    parts.forEach((p, i) => {
      const btn = el("button", {
        class: "modal__part" + (i === 0 ? " is-active" : ""),
        type: "button",
        "data-part-index": String(i),
        "data-part-file": p.file,
        text: p.label
      });
      host.appendChild(btn);
    });
  }

  function loadModalPart(i) {
    const entry = state.filtered[state.modalIdx];
    if (!entry || !entry.parts || !entry.parts[i]) return;
    const part = entry.parts[i];
    const v = $("[data-modal-video]");
    if (!v) return;
    gsap.to(v, {
      opacity: 0, duration: 0.3, ease: "power2.out",
      onComplete: () => {
        v.src = fileURL(part.file);
        v.load();
        v.play().catch(() => {});
        gsap.to(v, { opacity: 1, duration: 0.4, ease: "power2.out" });
      }
    });
    $$(".modal__part").forEach((b) => {
      b.classList.toggle("is-active", Number(b.getAttribute("data-part-index")) === i);
    });
  }

  function populateModal() {
    const entry = state.filtered[state.modalIdx];
    if (!entry) return;
    const total = state.filtered.length;
    const prev = entryAt(state.modalIdx - 1);
    const next = entryAt(state.modalIdx + 1);

    setText($("[data-modal-title]"), (entry.title || "").toUpperCase());
    setText($("[data-modal-num]"),   pad2(state.modalIdx + 1));
    setText($("[data-modal-total]"), pad2(total));
    setText($("[data-modal-desc]"),  entry.description || "");
    setText($("[data-modal-prev-title]"), (prev.title || "").toUpperCase());
    setText($("[data-modal-next-title]"), (next.title || "").toUpperCase());

    renderModalParts(entry);

    const part = entry.parts && entry.parts[0];
    const v = $("[data-modal-video]");
    if (v && part) {
      v.src = fileURL(part.file);
      v.load();
      v.play().catch(() => {});
    }
  }

  function openModal(idx) {
    const lb = $("[data-modal]");
    if (!lb) return;
    state.modalIdx = ((idx % state.filtered.length) + state.filtered.length) % state.filtered.length;
    state.modalOpen = true;
    populateModal();
    lb.hidden = false;
    lb.setAttribute("aria-hidden", "false");
    document.body.style.overflow = "hidden";
    document.body.classList.add("is-modal");
    requestAnimationFrame(() => lb.classList.add("is-open"));
  }

  function closeModal() {
    const lb = $("[data-modal]");
    if (!lb) return;
    state.modalOpen = false;
    lb.classList.remove("is-open");
    document.body.classList.remove("is-modal");
    const v = $("[data-modal-video]");
    if (v) v.pause();
    setTimeout(() => {
      lb.hidden = true;
      lb.setAttribute("aria-hidden", "true");
      if (v) { v.removeAttribute("src"); try { v.load(); } catch {} }
      document.body.style.overflow = "";
    }, 320);
  }

  function modalAdvance(dir) {
    state.modalIdx = ((state.modalIdx + dir) % state.filtered.length + state.filtered.length) % state.filtered.length;
    populateModal();
  }

  function wireModal() {
    // Spinner: visible while the modal video is buffering. The video element
    // persists across opens/part-swaps, so listeners are bound once here.
    const spinner = $("[data-modal-spinner]");
    const modalVid = $("[data-modal-video]");
    const showSpinner = () => spinner && spinner.classList.add("is-visible");
    const hideSpinner = () => spinner && spinner.classList.remove("is-visible");
    if (modalVid) {
      modalVid.addEventListener("loadstart", showSpinner);
      modalVid.addEventListener("waiting",   showSpinner);
      modalVid.addEventListener("stalled",   showSpinner);
      modalVid.addEventListener("playing",   hideSpinner);
      modalVid.addEventListener("canplay",   hideSpinner);
      modalVid.addEventListener("error",     hideSpinner);
      modalVid.addEventListener("emptied",   hideSpinner);
    }

    // Open from center frame
    const frame = $("[data-frame]");
    if (frame) frame.addEventListener("click", () => openModal(state.idx));

    // Open from list rows
    const list = $("[data-list-rows]");
    if (list) {
      list.addEventListener("click", (ev) => {
        const row = ev.target.closest("[data-list-row]");
        if (!row) return;
        const i = Number(row.getAttribute("data-idx"));
        openModal(i);
      });
    }

    // Close (backdrop, close button)
    $$("[data-modal-close]").forEach((el2) => el2.addEventListener("click", closeModal));

    // Modal prev/next
    const mp = $("[data-modal-prev]");
    const mn = $("[data-modal-next]");
    if (mp) mp.addEventListener("click", () => modalAdvance(-1));
    if (mn) mn.addEventListener("click", () => modalAdvance(1));

    // Parts tab clicks
    const partsHost = $("[data-modal-parts]");
    if (partsHost) {
      partsHost.addEventListener("click", (ev) => {
        const btn = ev.target.closest(".modal__part");
        if (!btn) return;
        loadModalPart(Number(btn.getAttribute("data-part-index")));
      });
    }

    // Keyboard: Esc closes; [/] navigate projects; ←/→ switch parts
    document.addEventListener("keydown", (ev) => {
      if (!state.modalOpen) return;
      if (ev.key === "Escape") { ev.preventDefault(); closeModal(); return; }
      if (ev.key === "[") { ev.preventDefault(); modalAdvance(-1); return; }
      if (ev.key === "]") { ev.preventDefault(); modalAdvance(1); return; }
      const entry = state.filtered[state.modalIdx];
      if (!entry || !entry.parts || entry.parts.length <= 1) return;
      const cur = $$(".modal__part").findIndex((b) => b.classList.contains("is-active"));
      if (ev.key === "ArrowRight") { ev.preventDefault(); loadModalPart((cur + 1) % entry.parts.length); }
      else if (ev.key === "ArrowLeft") { ev.preventDefault(); loadModalPart((cur - 1 + entry.parts.length) % entry.parts.length); }
    });
  }

  // ---------- Wire interactions ----------

  // ---------- Scroll transition (page-flip via GSAP timeline) ----------
  //
  // When direction = +1 (next):
  //   - bottom floater rises off-screen (the "next" preview moves toward center)
  //   - top floater rises off-screen too (the "prev" preview is replaced)
  //   - center frame + bg crossfade
  //   - meta strips fade
  //   - mid-timeline → renderSlider() swaps content
  //   - new floaters slide in from above (top) and below (bottom)
  //   - new center frame + meta strips fade in
  //
  // direction = -1 (prev) reverses the slide direction on the floaters.
  // The whole transition is ~900ms, locked behind a single isAnimating flag
  // so rapid wheel events don't queue up multiple transitions.
  let isAnimating = false;

  function transitionTo(direction) {
    if (isAnimating) return;
    if (state.filtered.length < 2) return;
    isAnimating = true;
    const sign = direction >= 0 ? 1 : -1;

    const tl = gsap.timeline({
      defaults: { ease: "power3.inOut" },
      onComplete: () => { isAnimating = false; }
    });

    // OUTGOING: 0 → 0.45s
    tl.to(".bg-video",                             { opacity: 0, duration: 0.4, ease: "power2.in" }, 0);
    tl.to("[data-frame-video]",                    { opacity: 0, duration: 0.4, ease: "power2.in" }, 0);
    tl.to("[data-frame-kind], [data-frame-pagination]", { y: -8 * sign, opacity: 0, duration: 0.35, ease: "power2.in" }, 0);
    // Floaters slide in the direction of travel: next-scroll (sign=+1) sends
    // both floaters UP; prev-scroll sends both DOWN.
    tl.to(".floater--top",    { y: -120 * sign, opacity: 0, duration: 0.45, ease: "power2.in" }, 0);
    tl.to(".floater--bottom", { y: -120 * sign, opacity: 0, duration: 0.45, ease: "power2.in" }, 0);

    // SWAP CONTENT at 0.45s — instant DOM update while everything is hidden.
    tl.add(() => {
      state.idx = sign > 0 ? nextIdx() : prevIdx();
      renderSlider();
      // Pre-set entry positions for the incoming side so the first frame
      // of the IN tween is correct (no flash of unanimated content).
      gsap.set(".floater--top",    { y: 120 * sign, opacity: 0 });
      gsap.set(".floater--bottom", { y: 120 * sign, opacity: 0 });
      gsap.set("[data-frame-kind], [data-frame-pagination]", { y: 8 * sign, opacity: 0 });
    }, 0.45);

    // INCOMING: 0.45s → 0.9s
    tl.to(".bg-video",                             { opacity: 0.85, duration: 0.5, ease: "power3.out" }, 0.45);
    tl.to("[data-frame-video]",                    { opacity: 1, duration: 0.5, ease: "power3.out" }, 0.45);
    tl.to(".floater--top",                         { y: 0, opacity: 0.55, duration: 0.6, ease: "power3.out" }, 0.45);
    tl.to(".floater--bottom",                      { y: 0, opacity: 0.55, duration: 0.6, ease: "power3.out" }, 0.45);
    tl.to("[data-frame-kind], [data-frame-pagination]", { y: 0, opacity: 1, duration: 0.5, ease: "power3.out" }, 0.5);
  }

  function wireSliderEvents() {
    const prevBtn = $("[data-floater-prev]");
    const nextBtn = $("[data-floater-next]");
    if (prevBtn) prevBtn.addEventListener("click", () => transitionTo(-1));
    if (nextBtn) nextBtn.addEventListener("click", () => transitionTo(1));

    // Hover-to-play on floaters: animate opacity to 1, load + play the clip on enter;
    // animate opacity back to 0.55 + pause on leave. GSAP-driven so it overrides any
    // inline opacity left over from the entry/transition timelines.
    const bindHoverPlay = (btn) => {
      if (!btn) return;
      const v = btn.querySelector("video");
      if (!v) return;
      btn.addEventListener("pointerenter", () => {
        gsap.to(btn, { opacity: 1, duration: 0.25, ease: "power2.out", overwrite: "auto" });
        v.play().catch(() => {});
      });
      btn.addEventListener("pointerleave", () => {
        gsap.to(btn, { opacity: 0.55, duration: 0.25, ease: "power2.out", overwrite: "auto" });
        v.pause();
      });
    };
    bindHoverPlay(prevBtn);
    bindHoverPlay(nextBtn);


    // Wheel: a single gesture should advance once. Lock during animation.
    let wheelAccum = 0;
    const WHEEL_THRESHOLD = 40;
    window.addEventListener("wheel", (ev) => {
      if (state.view !== "slider") return;
      if (state.modalOpen) return;
      if (isAnimating) { wheelAccum = 0; return; }
      wheelAccum += ev.deltaY;
      if (Math.abs(wheelAccum) < WHEEL_THRESHOLD) return;
      const dir = wheelAccum > 0 ? 1 : -1;
      wheelAccum = 0;
      transitionTo(dir);
    }, { passive: true });

    // Touch: single-finger swipe advances once. Vertical mirrors the wheel
    // (swipe up = next), horizontal follows the natural slider gesture
    // (swipe left = next). Whichever axis has more displacement wins.
    const sliderEl = $("[data-slider]");
    if (sliderEl) {
      const SWIPE_THRESHOLD = 40;
      let touchStartX = 0;
      let touchStartY = 0;
      let touchActive = false;
      sliderEl.addEventListener("touchstart", (ev) => {
        if (state.view !== "slider" || state.modalOpen || isAnimating) {
          touchActive = false;
          return;
        }
        if (ev.touches.length !== 1) { touchActive = false; return; }
        touchStartX = ev.touches[0].clientX;
        touchStartY = ev.touches[0].clientY;
        touchActive = true;
      }, { passive: true });
      sliderEl.addEventListener("touchend", (ev) => {
        if (!touchActive) return;
        touchActive = false;
        if (state.view !== "slider" || state.modalOpen || isAnimating) return;
        const t = ev.changedTouches[0];
        if (!t) return;
        const dx = t.clientX - touchStartX;
        const dy = t.clientY - touchStartY;
        const absX = Math.abs(dx);
        const absY = Math.abs(dy);
        if (Math.max(absX, absY) < SWIPE_THRESHOLD) return;
        const dir = absY >= absX
          ? (dy < 0 ? 1 : -1)   // swipe up = next, swipe down = prev
          : (dx < 0 ? 1 : -1);  // swipe left = next, swipe right = prev
        transitionTo(dir);
      }, { passive: true });
      sliderEl.addEventListener("touchcancel", () => { touchActive = false; }, { passive: true });
    }

    // Keyboard: arrow keys advance.
    document.addEventListener("keydown", (ev) => {
      if (state.view !== "slider" || state.modalOpen) return;
      if (isAnimating) return;
      if (ev.key === "ArrowDown" || ev.key === "PageDown") {
        ev.preventDefault();
        transitionTo(1);
      } else if (ev.key === "ArrowUp" || ev.key === "PageUp") {
        ev.preventDefault();
        transitionTo(-1);
      }
    });
  }

  function wireFilterEvents() {
    const host = $("[data-filters]");
    if (!host) return;
    host.addEventListener("click", (ev) => {
      const btn = ev.target.closest("[data-filter-id]");
      if (!btn) return;
      const id = btn.getAttribute("data-filter-id");
      applyFilter(id);
      renderFilters();
      renderSlider();
      renderList();
    });
  }

  // ---------- Tagline auto-fit ----------
  // Sizes the LEFT half to fill its container, applies the same size (capped)
  // to the RIGHT half so "In Motion" never reads larger than the left, and
  // additionally caps both halves at 50% of the center frame's height so the
  // title never overpowers the video.
  function fitTagline() {
    const halves = [
      { container: $(".tagline--left"),  node: $(".tagline--left .tagline__line") },
      { container: $(".tagline--right"), node: $(".tagline--right .tagline__line") }
    ];

    // Natural fit-to-width size for each half.
    const sizes = halves.map(({ container, node }) => {
      if (!container || !node || container.clientWidth <= 0) return 0;
      node.style.fontSize = "100px";
      const naturalWidth = node.scrollWidth;
      if (naturalWidth <= 0) return 0;
      return (100 * container.clientWidth) / naturalWidth;
    });

    // Hard cap: 50% of the center frame's rendered height.
    const frame = $(".frame");
    const frameHeight = frame ? frame.getBoundingClientRect().height : 0;
    const maxByFrame = frameHeight > 0 ? frameHeight * 0.5 : Infinity;

    const leftSize     = sizes[0] || 0;
    const rightSize    = sizes[1] || 0;
    const cappedLeft   = Math.min(leftSize, maxByFrame);
    // Right also capped at left's actual applied size (so left stays the visual lead).
    const cappedRight  = Math.min(rightSize, cappedLeft || rightSize, maxByFrame);

    if (halves[0].node && cappedLeft  > 0) halves[0].node.style.fontSize = cappedLeft  + "px";
    if (halves[1].node && cappedRight > 0) halves[1].node.style.fontSize = cappedRight + "px";
  }

  // ---------- Reveal animations ----------

  function animateInitialReveal() {
    if (!window.gsap) return;

    const frameEl   = $(".frame");
    const frameW    = frameEl ? frameEl.getBoundingClientRect().width : 0;
    const inset     = (frameW / 2) + 12;
    const TOGETHER_GAP = 24;
    const closeInset = Math.max(0, inset - (TOGETHER_GAP / 2));

    const leftHalf  = $(".tagline--left");
    const leftLine  = $(".tagline--left .tagline__line");
    const rightHalf = $(".tagline--right");

    // ---- Initial state: left tagline becomes the centered counter ----
    if (leftHalf) leftHalf.classList.add("is-centering");
    if (leftLine) leftLine.textContent = "00 Years";
    gsap.set(leftHalf,  { opacity: 0 });
    // Right tagline starts fully off-screen to the right so it can slide in
    // from the viewport edge during phase 4.
    const rightOffsetIn = (rightHalf ? rightHalf.getBoundingClientRect().width : 400) + 60;
    gsap.set(rightHalf, { opacity: 0, x: rightOffsetIn });

    const tl = gsap.timeline({
      defaults: { ease: "power3.out" },
      onComplete: () => document.body.classList.remove("is-intro")
    });

    // ---- Phase 1: counter fades in centered ----
    tl.to(leftHalf, { opacity: 1, duration: 0.4 }, 0);

    // ---- Phase 2: count 00 → 20, one integer at a time (no skipping) ----
    // Linear ease + snap to integers guarantees each value holds for an equal slice
    // (1.4s / 20 = 70ms per tick) regardless of frame rate.
    const counter = { n: 0 };
    tl.to(counter, {
      n: 20,
      duration: 1.4,
      ease: "none",
      snap: { n: 1 },
      onUpdate: () => {
        if (leftLine) {
          leftLine.textContent = String(counter.n).padStart(2, "0") + " Years";
        }
      }
    }, 0.4);

    // ---- Phase 3: snap to "20+ Years", brief hold ----
    tl.call(() => { if (leftLine) leftLine.textContent = "20+ Years"; });
    tl.to({}, { duration: 0.35 });

    // ---- Phase 4: slide over for IN MOTION ----
    // Switch left tagline back to its fitted right-aligned container, then
    // pre-set GSAP x so the text stays visually at the viewport center the
    // instant the class is removed. After that, both halves animate to their
    // close-together positions and the right half fades in.
    tl.call(() => {
      if (!leftHalf) return;
      leftHalf.classList.remove("is-centering");
      fitTagline();
      gsap.set(leftHalf, { x: inset });   // text's right edge sits at viewport center
    });
    tl.to(leftHalf,  { x: closeInset,  duration: 0.7, ease: "power3.out" });
    tl.to(rightHalf, { x: -closeInset, opacity: 1,    duration: 0.7, ease: "power3.out" }, "<");

    // ---- Phase 5: hold (both halves close together) ----
    tl.to({}, { duration: 0.35 });

    // ---- Phase 6: spread + frame fills the gap ----
    tl.to(leftHalf,        { x: 0, duration: 0.95, ease: "expo.inOut" });
    tl.to(rightHalf,       { x: 0, duration: 0.95, ease: "expo.inOut" }, "<");
    tl.from("[data-frame]", { scale: 0.85, opacity: 0, duration: 0.95, ease: "power3.out" }, "<+0.1");

    // ---- Phase 7: rest of UI ----
    tl.fromTo(".bg-video", { opacity: 0 }, { opacity: 0.85, duration: 1.0 }, "<+0.2");
    tl.from(".bg-noise",                      { opacity: 0, duration: 0.6 }, "<");
    tl.from(".chrome--top",                   { y: -30, opacity: 0, duration: 0.5 }, "<");
    tl.from(".chrome--bottom",                { y: 30,  opacity: 0, duration: 0.5 }, "<");
    tl.from(".scale",                         { opacity: 0, duration: 0.5 }, "<");
    tl.from("[data-frame-kind]",              { y: 20, opacity: 0, duration: 0.4 }, "<+0.1");
    tl.from("[data-frame-pagination]",        { y: -20, opacity: 0, duration: 0.4 }, "<");
    tl.fromTo(".floater--top",    { opacity: 0 }, { opacity: 0.55, duration: 0.5 }, "<");
    tl.fromTo(".floater--bottom", { opacity: 0 }, { opacity: 0.55, duration: 0.5 }, "<");
    return tl;
  }

  // ---------- Bootstrap ----------

  loadManifest()
    .then((data) => {
      state.entries = Array.isArray(data.entries) ? data.entries : [];
      applyFilter("ALL");
      // Land on a random featured project so the slider doesn't always open on the same entry.
      const featuredIdxs = state.filtered.reduce((acc, e, i) => (e.featured ? (acc.push(i), acc) : acc), []);
      if (featuredIdxs.length) {
        state.idx = featuredIdxs[Math.floor(Math.random() * featuredIdxs.length)];
      }
      fitTagline();
      // Re-fit when viewport changes — frame width and available zone shift with vw.
      let resizeRaf = 0;
      window.addEventListener("resize", () => {
        cancelAnimationFrame(resizeRaf);
        resizeRaf = requestAnimationFrame(fitTagline);
      });
      // Re-fit once fonts have settled (first measurement may use fallback metrics).
      if (document.fonts && document.fonts.ready) {
        document.fonts.ready.then(fitTagline);
      }
      renderScaleMarkers();
      renderFilters();
      renderSlider();
      renderList();
      wireSliderEvents();
      wireFilterEvents();
      wireViewToggle();
      bindListHover();
      wireModal();
      window.__WJY_V2__ = state;
      requestAnimationFrame(() => {
        revealPage();
        animateInitialReveal();
      });
    })
    .catch((err) => {
      console.error("Failed to load manifest:", err);
      renderError("The manifest at videos.json failed to load. Try refreshing.");
      revealPage();
    });
})();
